CXXFLAGS += -std=c++17 -Wall -I. -O2
LDFLAGS  +=
CXX      := g++

all: \
hw01_01 \
hw01_02 \
hw01_03 \
hw01_04 \
hw01_05 \
hw01_06 \
hw01_07 \
hw01_08 \
hw01_09 \
hw01_10 \
hw01_11 \
hw01_12 \
hw01_13 \
hw01_14 \
hw01_15 \
hw01_18 \
hw01_19 \
hw01_20 \
hw01_21 \
hw01_22 \
hw01_23 \
hw01_24 \
hw01_25 \

clean:
	find . -name '*.o' -exec rm -f {} \;
	find . -name '*.a' -exec rm -f {} \;
	find . -name '*.d' -exec rm -f {} \;
	find . -name 'hw01_*' -exec rm -f {} \;

hw01_01: src_01.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_01.cpp

hw01_02: src_02.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_02.cpp

hw01_03: src_03.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_03.cpp

hw01_04: src_04.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_04.cpp

hw01_05: src_05.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_05.cpp

hw01_06: src_06.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_06.cpp

hw01_07: src_07.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_07.cpp

hw01_08: src_08.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_08.cpp

hw01_09: src_09.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_09.cpp

hw01_10: src_10.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_10.cpp

hw01_11: src_11.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_11.cpp

hw01_12: src_12.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_12.cpp

hw01_13: src_13.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_13.cpp

hw01_14: src_14.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_14.cpp

hw01_15: src_15.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_15.cpp

hw01_18: src_18.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_18.cpp

hw01_19: src_19.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_19.cpp

hw01_20: src_20.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_20.cpp

hw01_21: src_21.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_21.cpp

hw01_22: src_22.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_22.cpp

hw01_23: src_23.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_23.cpp

hw01_24: src_24.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_24.cpp

hw01_25: src_25.cpp
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ src_25.cpp
